### ISSUE TITLE
.Group().Send() failing silently

### ISSUE THREAD

**Issue by ChrisLincoln** [OrleansContrib/SignalR.Orleans#114]
I am in the process of upgrading an ASP.NET web api from .NET Core 2.2 to 3.1. The Web API is an orleans client whose grains send signalR messages via this backplane.  Prior to the upgrade, things worked.  Now, when I call

await _grainFactory.GetHub<IFooHub>()
                .Group("somegroup")
                .Send(nameof(IClientMethods.FooEvent), msg);

I do not receive the message at the client endpoint, and see no evidence of it in the browser's network WS tab.  I've verified the signalR plumbing by sending dummy messages from the Web API to the client, and those are coming through fine.

I've followed this guide: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio). I know we have always had startup order depenency issues with our silo & web api, so I am leary of the changes I made in the web app. The order of things may have changed in a significant way. 

The ASP.Net app is at .Net Core 3.1
The Silo app is at Orleans 3.1.1
This library is 1.5

As an extra data point, I am not seeing any of the information ILogger messages coming from this library. I am seeing my own information level messages.

**Comment by ChrisLincoln** [comment]
[ConnectionGrain.Send](https://github.com/OrleansContrib/SignalR.Orleans/blob/master/src/SignalR.Orleans/Core/ConnectionGrain.cs#L92)

State.Connections is always 0 members.

ConnectionGrain.Add() is getting called many times with the same connectionId. The logic is as though the State.Connections collection has never seen the id.  Do I have some sort of session storage mal-configured?

`public virtual async Task Add(string connectionId)
        {
            var shouldWriteState = State.Connections.Add(connectionId);
            if (!_connectionStreamHandles.ContainsKey(connectionId))
            {
                var clientDisconnectStream = _streamProvider.GetStream<string>(Constants.CLIENT_DISCONNECT_STREAM_ID, connectionId);
                var subscription = await clientDisconnectStream.SubscribeAsync(async (connId, _) => await Remove(connId));
                _connectionStreamHandles[connectionId] = subscription;
            }

            if (shouldWriteState)
                await WriteStateAsync();
        }`

**Comment by chillitom** [comment]
Was this ever resolved?  This is the closest description to something I am seeing with a Client and Silo working nicely with Localhost clustering but then failing silently on KubernetesClustering.

**Comment by ChrisLincoln** [comment]
@chillitom Sorry, we abandoned the use of the lib some time ago.  It was never resolved for us.  I should close this, though, since I won't be here to see it through.

**Comment by zengyun261** [comment]
The interface name of the hub must be `I{Hub Class Name}`

`_hubName = hubType.IsInterface && hubType.Name.StartsWith("I")
              ? hubType.Name.Substring(1)
              : hubType.Name;`
