### ISSUE TITLE
UseSignalR() should not call AddApplicationPart()

### ISSUE THREAD

**Issue by yoDon** [OrleansContrib/SignalR.Orleans#137]
The `SignalR.Orleans` `UseSignalR()` function is currently forcing callers to do a bunch of additional work in their projects to explicitly list all the grain types they are using. This extra work isn't normally required when using Orleans and shouldn't be required in order to use `SignalR.Orleans`.

Orleans provides an optional `AddApplicationPart()` function that allows a project to explicitly register grain types. By default, there is no need to call `AddApplicationPart()` because Orleans automatically finds and includes all available grain types. For many projects, this default Orleans behavior is desirable.

The problem is that if any code in the project calls `AddApplicationPart()` to register even a single grain type, the automatic grain type registration code gets shut off and all grain types need to be added explicitly. `SignalR.Orleans` currently calls `AddApplicationPart()`.

`SignalR.Orleans` needs access to the `IClientGrain` grain type. It looks like someone at some point added code that is theoretically helpful, namely
```
.ConfigureApplicationParts(delegate (IApplicationPartManager parts)
{
    parts.AddApplicationPart(typeof(IClientGrain).Assembly).WithReferences();
})
```
in the hopes that callers would not need to call `AddApplicationPart(...)` themselves when using `SignalR.Orleans`, but in doing so they unintentionally forced all callers to explicitly add all other grains included in the calling project, whether the caller wants to or not.

Interestingly, the Sample code showing how to use the SignalR.Orleans library already explicitly adds the `IClientGrain` type, so the samples run just fine without the add statement that is currently baked into the `UseSignalR()` library function.

Fortunately, the fix is pretty simple. I'll submit a PR momentarily.

**Comment by galvesribeiro** [comment]
Thanks for the issue and PR. There was legitimate cases to have it there because of other problems that doesn't exist anymore. 

In fact, this is something that was removed on Orleans 7.

I'm going to merge now the PR and will release a new version for the 3.x, and then release a new one with the 7.

Thanks!

**Comment by bangonkali** [comment]
> In fact, this is something that was removed on Orleans 7.

Hi @galvesribeiro , how  do we do `ConfigureApplicationParts` for Orleans `7`? I can't seem to find reference for it. Tried ChatGPT and it only knows about Orleans `3.5.1`.
