### ISSUE TITLE
Alternative to Microsoft.AspNetCore.SignalR.Redis?

### ISSUE THREAD

**Issue by lawgorht** [OrleansContrib/SignalR.Orleans#28]
Hi,

I'm not sure if I understand this project correctly. What I am looking for is a Orleans alternative to Microsoft.AspNetCore.SignalR.Redis. I want to have a dedicated Orelans Cache cluster for SignalR that I can add to any SignalR Host like that: 

```
services.AddSignalR()
    .AddOrleans(option => {option.Options=orelanclusterconnectionoption});
```

The goal is to be able to send messages to SignalR clients from inside Grains. The Clients should be able to connect to any SignalR host with the specific hub.

Is that something I can achieve with this project?

Many thanks.

**Comment by galvesribeiro** [comment]
@lawgorht Hey!

You are correct. This project add a backplane to SignalR using Orleans, just like you have with Redis. 

Also, it gives you the ability to send messages from grain code to SignalR clients thru a hub in a transparent way. Check the README.md on the root of the repository for a quick sample on how to do that.

**Comment by galvesribeiro** [comment]
The ClientConfiguration is not used anymore on Orleans 2.0+. Are you trying to use it on < 2.0 by chance?

**Comment by lawgorht** [comment]
I'm struggling before the configuration, my code can't find the `AddOrleans ` method.

```
public void ConfigureServices(IServiceCollection services)
{
            services.AddSignalR().AddOrleans();
}
```

this shows me the error _"ISignalRBuilder" does not contain a definition for "AddOrleans" and no extension method...."_ Am I missing a dependency here?

**Comment by claylaut** [comment]
@lawgorht, now the configuration is simpler and all you need to do is:
`UseSignalR()` on `IClientBuilder`
`UseSignalR()` on `ISiloHostBuilder`

then what you need to do is register actual SignalR by using `.AddSignalR()` on `IServiceCollection` (this is part of `Microsoft.AspNetCore.SignalR` nuget package).

That's it :)

**Comment by galvesribeiro** [comment]
@lawgorht the README.md was updated by @claylaut reflecting that sample.

I'm closing the issue as it may be the answer for your question. Feel free to re-open in case you fall into throuble again.

**Comment by claylaut** [comment]
@lawgorht, you were right, there was an issue cause I was registering within orleans configureServices and it was creating a new DI Container internally.

Now I've re-added the `.addOrleans`. + updated example usage 

https://github.com/OrleansContrib/SignalR.Orleans#client

**Comment by lawgorht** [comment]
@claylaut thanks for letting me know. I will give it a next try maybe this holidays. Btw it seems tat SignalR.Orleans it still uses Microsoft.AspNetCore.SignalR.Core 1.0.0-alpha2-final instead of 1.0.0-preview1-final. I gave it a very short try to upgrade but failed on `InvokeLocal`.

**Comment by claylaut** [comment]
The reason why we're still using `1.0.0-alpha2-final ` since the new version is dependant on .net core 2.1 preview. which I don't want to upgrade it to .net core 2.1 preview yet since its too risky, you need to use visual studio 2017 preview, etc.

Also there are people like us which currently are using this on production :)

**Comment by lawgorht** [comment]
thanhks, I'll just wait for the dust to settle:)
