### ISSUE TITLE
Best approach when a server is lost or restarted?

### ISSUE THREAD

**Issue by githubuser25** [OrleansContrib/SignalR.Orleans#54]
Since the client and group grains are stored in memory, when a server is lost or restarted they are too lost. I read that some of you are currently using this in a production environment. How are you handling this?

**Comment by claylaut** [comment]
@githubuser25, sorry for the late reply. Currently this is not supported. I've opened a PR with a fix. once this has been merged and released you will be able to override the grain persistence by registering your desired storage provider with the following constant. `Constants.GrainPersistence`.

**Comment by claylaut** [comment]
@githubuser25,
The request change has been release with version `1.1.1`

This is can easily be done by doing the following example on the `SiloHostBuilder`:
```cs
.UseSignalR(new SignalrServerConfig
{
	ConfigureBuilder = (hostBuilder, config) =>
	{
		hostBuilder
			.AddMemoryGrainStorage(config.PubSubProvider) // you can change this as you wish
			.AddMemoryGrainStorage(config.StorageProvider);
	}
});			
```

**important** please note that this release contains the following changes as well.
https://github.com/OrleansContrib/SignalR.Orleans/releases/tag/1.1.1

Hope this helps.

**Comment by seniorquico** [comment]
@claylaut What about an frontend/ASP.NET Core server loss or restart? Could we end up in a situation where a client disconnected event doesn't flow back to the grains and, grain state persistence or not, we keep pumping events to a stream for a non-existent server?

**Comment by claylaut** [comment]
@seniorquico for frontend I recommend you use https://github.com/sketch7/signalr-client it handles a lot of extra features out of the box and its build on signalr client. One of the main features it has auto reconnection on all the open subcriptions you currently have and it is fully reactive which is big plus when it comes to realtime development.

You can see the full features list here: https://github.com/sketch7/signalr-client#features

PS. I m the Author of this library as well and I've been using in Production over 1year 3months+ now combined with Signalr Orleans.
