### ISSUE TITLE
Dependency injection and IClusterClient

### ISSUE THREAD

**Issue by seniorquico** [OrleansContrib/SignalR.Orleans#64]
After following the simple steps in this project's README, a user encountered the following error on the client side (details posted on [StackOverflow](https://stackoverflow.com/q/55084159/2709066)):

> Unable to resolve service for type 'Orleans.IClusterClient' while attempting to activate 'SignalR.Orleans.DefaultClusterClientProvider'.'

It appears that the `services.AddSignalR().AddOrleans()` call registers a `DefaultClusterClientProvider` that [expects an `IClusterClient`](https://github.com/OrleansContrib/SignalR.Orleans/blob/9f1d117b3a694b66905caf29f72273bf806821cc/src/SignalR.Orleans/IClusterClientProvider.cs#L14) to be explicitly registered in the `IServiceCollection`. Should this be mentioned in the README? Or is there a better example demonstrating how to configure SignalR.Orleans?

**Comment by galvesribeiro** [comment]
Hello!

The intent for that sample is that it assumes `IClusterClient` is already added to the DI container. That said, the `DefaultClusterClientProvider` assumes it. If you want to add a custom way to _provide_ the `IClusterClient`, you can just implement your own `IClusterClientProvider`.

Perhaps a note on README explaining that would be useful.

Will check on that later on. Thanks for the report.

**Comment by binhlt0402** [comment]
Hello!

I'm the OP of the StackOverflow post. Even after I registered IClusterClient in IServiceCollection using AddSingleton(client) I got another error whenever I call a grain.
![dotnet_GRaVQlAUfA](https://user-images.githubusercontent.com/35665483/54622266-e0001980-4a9b-11e9-8f3d-20e73f61ec08.png)
I attached the project here so you can check it out. I literally use the helloworld sample of orleans and the helloworld sample of signalr to create this demo.
[DemoSignalR.Orleans.zip](https://github.com/OrleansContrib/SignalR.Orleans/files/2984355/DemoSignalR.Orleans.zip)
