### ISSUE TITLE
use as back plan

### ISSUE THREAD

**Issue by SalimiHabib** [OrleansContrib/SignalR.Orleans#66]
hi
is this project can be use as a back plan for signalr by Microsoft orleans ?
thank you 
salimi

**Comment by claylaut** [comment]
@SalimiHabib, Yes this is a backplane for Signalr Orleans. Still, this was developed as an open source contribution and not officially by Microsoft.

Follow the installation and configuration steps: https://github.com/OrleansContrib/SignalR.Orleans#installation

Thanks.

**Comment by SalimiHabib** [comment]
Thanks for your time
