### ISSUE TITLE
[Documentation] Requiring same named interfaces.

### ISSUE THREAD

**Issue by bnowlin** [OrleansContrib/SignalR.Orleans#68]
Our application only has 1 hub and as an aid to self-documenting my interfaces where "IHubMethods" and "IClientMethods". They held the name of the methods the signalR client could call on our back-end and the methods the back-end could call on our signalR client. 

Our hub's name was not "HubMethods" so calling the client through Orleans always failed silently. Orleans HubContext when given an interfaces assumes the hub name is the interface - I. 

https://github.com/OrleansContrib/SignalR.Orleans/blob/master/src/SignalR.Orleans/Core/HubContext.cs

**Comment by galvesribeiro** [comment]
Not sure I understand the problem. Can you elaborate more and show some code sample?

@claylaut what do you think?

**Comment by bnowlin** [comment]
Hub:
`public class FooHub: Hub<IClientMethods>, IHubMethods`
Use of hub:
`_grainFactory.GetHub<IHubMethods>`

The above fails silently since SignalR.Orleans looks up the concrete class by sub-stringing the interface name. It was quick fix once we figured it out. I posted here because it bugged me for ~5 days. The post is a suggestion to add to documentation.

From src/SignalR.Orleans/Core/HubContext.cs
`_hubName = hubType.IsInterface && hubType.Name.StartsWith("I")
                ? hubType.Name.Substring(1)
                : hubType.Name;`

**Comment by claylaut** [comment]
I will look into it

**Comment by claylaut** [comment]
this will be fixed once this PR https://github.com/OrleansContrib/SignalR.Orleans/pull/71  has been merged.

**Comment by stephenlautier** [comment]
@claylaut no this one hasn't been fixed in my PR yet
