### ISSUE TITLE
Use SignalR UserIdentifier instead of user name

### ISSUE THREAD

**Issue by pashchuk** [OrleansContrib/SignalR.Orleans#70]
There is a `todo` to use UserIdentifier instead of user name for a particular user grain activation.  SignalR has been released with UserIdentifier property so now it's a good time to implement this todo: 
https://github.com/OrleansContrib/SignalR.Orleans/blob/master/src/SignalR.Orleans/OrleansHubLifetimeManager.cs#L114

**Comment by galvesribeiro** [comment]
@claylaut what you think about this?

**Comment by claylaut** [comment]
@galvesribeiro I will do this today or tomorrow morning since i need to test it.

**Comment by claylaut** [comment]
this will be fixed once this PR https://github.com/OrleansContrib/SignalR.Orleans/pull/71  has been merged.

**Comment by stephenlautier** [comment]
@galvesribeiro you should be able to close this one

**Comment by galvesribeiro** [comment]
Yeah, it is on the nuget package already. Thanks for the reminder.
