### ISSUE TITLE
Messages are being dispatched multiple times

### ISSUE THREAD

**Issue by stephenlautier** [OrleansContrib/SignalR.Orleans#79]
Recently I noticed that some messages are being received multiple times on the client.

After debugging a little bit, I found out that it is actually being dispatched from the server multiple times

### Messages being dispatched multiple times
![image](https://user-images.githubusercontent.com/3908723/59192394-8ed76180-8b82-11e9-9270-8f55aaf6fa15.png)

### Streams initializing multiple times

![image](https://user-images.githubusercontent.com/3908723/59192853-1f627180-8b84-11e9-9402-b54b69e5d272.png)

After some digging, I believe this commit introduced the issue
https://github.com/OrleansContrib/SignalR.Orleans/commit/66ca0aa8395dd54e05f50ee93d076aa6ddc5fb61

What we can do is either call it again on the ctor, or else we can lock it?
Just seen Redis implementation they do both

Redis signalr interest points
- https://github.com/aspnet/SignalR/blob/master/src/Microsoft.AspNetCore.SignalR.StackExchangeRedis/RedisHubLifetimeManager.cs#L47
- https://github.com/aspnet/SignalR/blob/master/src/Microsoft.AspNetCore.SignalR.StackExchangeRedis/RedisHubLifetimeManager.cs#L500

I think there's is good because it won't lock if its already initialized.

Another note, to be honest, it's not that easily reproducible, however, on our server it happens pretty much 100% - we have 2 clients (x2 pods) and 1 client (x2 pod) connecting 6 in total

**Comment by galvesribeiro** [comment]
Oh! That is critical.

The Lock async is the best option.
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stephenlautier** [comment]
Yes its quite critical, @galvesribeiro want me to open a PR for it?

**Comment by galvesribeiro** [comment]
If you could I would appreciate that. I’ll review/merge/release right after it.
