### ISSUE TITLE
Ambiguous reference to UseSignalR

### ISSUE THREAD

**Issue by kimmccoy** [OrleansContrib/SignalR.Orleans#85]
I've updated to:
SignalR.Orleans 1.3.2
Microsoft.Orleans.Server 2.3.5

I now get an ambiguous reference for the UserSignalR method as follows:

```
 .UseSignalR(cfg => {
 ...
})
```

error CS0121: The call is ambiguous between the following methods or properties: 'Orleans.Hosting.SiloHostBuilderExtensions.UseSignalR(Orleans.Hosting.ISiloHostBuilder, System.Action<SignalR.Orleans.SignalrOrleansSiloHostConfigBuilder>)' and 'Microsoft.Extensions.DependencyInjection.OrleansServerExtensions.UseSignalR(Orleans.Hosting.ISiloHostBuilder, System.Action<SignalR.Orleans.SignalrServerConfig>)'

I see that the Microsoft.Extensions.DependencyInjection.OrleansServerExtensions is obsolete.

So if I change things a bit and try and only reference Orleans.Hosting.SiloHostBuilderExtensions I get another ambiguous reference to Orleans.Hosting.SiloHostBuilderExtensions which is in...
Orleans.Runtime.Abstractions, Version=2.0.0.0
and 
SignalR.Orleans, Version=1.3.2

It's this second problem that appears to be the real one as far as I can tell. 

Anyhow, seemed to have fixed it while writing this issue so maybe it is one for the documentation or perhaps renaming things a bit to avoid the conflict would be good.

This works - explicitly name the type SignalrOrleansSiloHostConfigBuilder :
```
 .UseSignalR((SignalrOrleansSiloHostConfigBuilder cfg) => {
    cfg.Configure((b, c) => {
        ...
    });
})
```

**Comment by stephenlautier** [comment]
hmm weird.. it seems its work fine for me

![image](https://user-images.githubusercontent.com/3908723/59527920-29b2a180-8edd-11e9-9f96-11f889142ca9.png)

perhaps different versions of c# it resolves differently, can you try to add in your csproj?

```
<PropertyGroup>
    <LangVersion>latest</LangVersion>
</PropertyGroup>
```

**Comment by kimmccoy** [comment]
I've got the 'latest' value in the config.

This works:

```
.UseSignalR(cfg => cfg.Configure((b, c) => { }))
or...
.UseSignalR()
```

But this comes up with ambiguous reference
between Orleans.Hosting.SiloHostBuilderExtensions.UseSignalR and Microsoft.Extensions.DependencyInjection.OrleansServerExtensions

```
.UseSignalR(cfg => { 
 // lots of useless commented out code goes here where I leave
//  a pointless argument in a method  that causes .net compiler to
// not know what it was meant to be doing with 'cfg'
})
```

While this does work:

````
 .UseSignalR((SignalrOrleansSiloHostConfigBuilder cfg) => { })
````

Which makes sense now as it is ambiguous what the argument types are, but only if there isn't any useful code in the right spot anyway.

It's a bit confusing when extensions methods collide and you want both namespaces at the top with 'using' statements.

My other problem with these two is probably not a problem as it only turned up while I was trying to work around the fist problem above.

Not a problem most likely...
Orleans.Hosting.SiloHostBuilderExtensions which is in...
Orleans.Runtime.Abstractions, Version=2.0.0.0
and
SignalR.Orleans, Version=1.3.2

**Comment by galvesribeiro** [comment]
You need to write something inside the delegate in order to remove the ambiguity. It is the same with all other extension methods around.
