### ISSUE TITLE
MessagePack Support 

### ISSUE THREAD

**Issue by alfkonee** [OrleansContrib/SignalR.Orleans#92]
I wanted to know if the current implementation of this Library support the messagepack protocol.

Preliminary  investigation show that on the client side it can be configured to use messagepack but there's no such config match on the silo Host Side (Server).

Is this scenario possible on the server side of things  if yes please point me to the necessary configs to apply if not I might be able to implement the  needed config point with necessary guidance from the community.

**Comment by galvesribeiro** [comment]
Hello!

Yes, it does.

https://github.com/OrleansContrib/SignalR.Orleans/blob/master/src/SignalR.Orleans/Extensions.cs#L67

You should call that on the SignalR configuration and then there you add the MessagePack protocol just like you would on a regular SignalR application.

**Comment by alfkonee** [comment]
In there no config needed on to Silo to support to the protocol??

**Comment by galvesribeiro** [comment]
Nop! Just on the client and on SignalR. It is not an Orleans concern.

**Comment by alfkonee** [comment]
Ok will try with  different config parameters and post my findings thanks

**Comment by alfkonee** [comment]
I got it working now,
@galvesribeiro  you were right it wasn't Orleans just pesky messagepack serialzation and deserialization Rules.

**Comment by alfkonee** [comment]
Gotta say learning a lot from this Library
Maybe will write a blog post after I'm done with the implementation I'm doing. 🤞🏾

**Comment by galvesribeiro** [comment]
Don't forget to share the link! Would love to read it! 😃
